# Site settings
title: Douglas MK - desenvolvedor web
email: douglas@douglasmk.com.br
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can  -dit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://douglasmk.com.br" # the base hostname & protocol for your site
twitter_username: douglasmk
github_username:  douglasmk

# Build settings
markdown: kramdown
